baseURL = 'https://arturchichorro.github.io/hugo-test-jt/'
languageCode = 'en-us'
title = 'João Lobo Fernandes'
theme = "lobo-theme"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\\[', '\\]'], ['$$', '$$']]
          inline = [['\\(', '\\)']]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Writing"
    url = "/blog/"
    weight = 2

[params]
    author = "João Lobo Fernandes"

[caches]
  [caches.images]
    dir = ':cacheDir/images'